# Top-level settings
target-version = "py313"
preview = true
exclude = [
  ".venv",
  "site",
  "build",
  "dist",
  "databricks/bundles/**/notebooks/*.py",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"

[lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "W",  # pycodestyle warnings
  "I",  # isort
  "B",  # flake8-bugbear
  "UP", # pyupgrade
]
ignore = []
fixable = ["ALL"]
unfixable = []

[lint.isort]
known-first-party = [
  "common",
  "pipelines",
  "etl_job",
  "golden_path",
]
combine-as-imports = true

[lint.per-file-ignores]
"**/tests/**" = ["S101"]


