copyright: 'Made with ❤️ by Oslo Origo

  '
docs_dir: ./docs
edit_uri: https://github.com/oslokommune/padda-golden-path/tree/main/docs
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/oslokommune
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/company/osloorigo
  - icon: fontawesome/solid/flask
    link: https://labs.oslo.kommune.no/
extra_css:
- stylesheets/admonitions.css
- stylesheets/extra.css
- stylesheets/punkt.css
markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.superfences:
    custom_fences:
    - class: mermaid
      format: !!python/name:mermaid2.fence.fence_mermaid_custom ''
      name: mermaid
- pymdownx.keys
- attr_list
nav:
- Home: index.md
- Implementering: architecture/progress.md
- Golden Paths:
  - Databricks Bundles:
    - Oversikt: golden-paths/databricks-bundles.md
    - API Ingestion Example - Databricks Asset Bundle: golden-paths/databricks-bundles/api_ingest.md
    - Excel to Gold - Databricks Asset Bundle: golden-paths/databricks-bundles/excel_to_gold.md
  - Generic Pipelines: golden-paths/generic-pipelines.md
- Guides:
  - Guider: guides/index.md
  - Data: guides/data/upload-excel-to-uc.md
  - Developer:
    - Dev Setup: guides/developer/dev-setup.md
    - Secrets: guides/developer/secrets.md
    - Upload Lib: guides/developer/upload-lib.md
- Notion-sider:
  - notion/index.md
  - Referansearkitektur: notion/arkitektur-wip.md
  - Github Struktur Iac Dab Ci Cd: notion/github-struktur-iac-dab-ci-cd.md
  - Tilgangsstyring Og Roller: notion/tilgangsstyring-og-roller.md
plugins:
- search
- mermaid2
- gen-files:
    scripts:
    - docs/mkdocs_extension/generate_guides_index.py
    - docs/mkdocs_extension/generate_listof_bundles.py
    - docs/mkdocs_extension/generate_notion_nav.py
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
repo_url: https://github.com/oslokommune/padda-golden-path
site_description: Golden paths, Databricks bundles, and shared libs
site_name: Padda Golden Path
site_url: https://oslokommune.github.io/padda-golden-path/
theme:
  favicon: assets/favicon.ico
  features:
  - content.action.edit
  - content.code.annotate
  - content.code.copy
  - content.tabs.link
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  - navigation.tabs
  - navigation.tracking
  icon:
    admonition:
      example: material/ship-wheel
    edit: material/pencil
    repo: fontawesome/brands/github
  logo: assets/oslologo.svg
  name: material
  palette:
  - scheme: oslo
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode
