[build-system]
requires = ["hatchling>=1.25"]
build-backend = "hatchling.build"

[tool.uv]

[tool.uv.workspace]
members = [
  "libs/padda.pipelines",
  "libs/padda.common"
]

[project]
name = "golden-path"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "mkdocs>=1.6.1",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-mermaid2-plugin>=1.2.3",
    "pyspark>=4.0.1",
    "requests>=2.32.5",
]

[tool.hatch.build.targets.wheel]
packages = ["src/golden_path"]

[project.optional-dependencies]
docs = [
  "mkdocs-material",
  "mkdocstrings[python]",
  "pymdown-extensions",
]
dev = [
  "pytest",
  "pytest-cov",
  "ruff",
  "pre-commit",
  "mkdocs-material",
  "mkdocstrings[python]",
  "pymdown-extensions",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "pytest-cov>=7.0.0",
]

[tool.pytest.ini_options]
pythonpath = [
  "src",
  "examples/api_ingest/src",
  "examples/etl/src",
]
