[project]
name = "vscode-demo"
version = "0.1.0"
description = "VS Code + Databricks demo project"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
]

[dependency-groups]
dev = [
    "databricks-connect",
    "pytest",
]

[project.scripts]
main = "vscode_demo.main:main"

[tool.hatch.build.targets.wheel]
packages = ["src/vscode_demo"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
