#!/usr/bin/env python3
"""Materialize bundle READMEs into docs and refresh mkdocs navigation."""

from collections.abc import Iterable
from pathlib import Path

try:
    import mkdocs_gen_files
except ImportError:  # pragma: no cover - available only during mkdocs builds
    mkdocs_gen_files = None

try:
    from ruamel.yaml import YAML

    def load_yaml(stream):
        yaml = YAML()
        yaml.preserve_quotes = True
        return yaml.load(stream)

    def dump_yaml(data, stream):
        yaml = YAML()
        yaml.preserve_quotes = True
        yaml.width = 4096
        yaml.indent(mapping=2, sequence=4, offset=2)
        yaml.dump(data, stream)

except ImportError:
    import yaml

    def load_yaml(stream):
        return yaml.safe_load(stream)

    def dump_yaml(data, stream):
        yaml.safe_dump(data, stream, default_flow_style=False, allow_unicode=True)


docs_dir = Path("docs")
bundles_dir = Path("examples")
index_doc_path = "golden-paths/databricks-bundles.md"
mkdocs_file = Path("mkdocs.yml")

if not bundles_dir.exists():
    print(f"Bundles directory not found: {bundles_dir}")
    exit(1)


def format_title(slug: str) -> str:
    return slug.replace("-", " ").replace("_", " ").title()


def extract_heading(markdown: str) -> str | None:
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()
    return None


def iter_bundle_readmes(paths: Iterable[Path]):
    for subdir in sorted(paths):
        if not subdir.is_dir():
            continue
        if not (subdir / "bundle.yml").exists():
            continue
        readme = subdir / "README.md"
        if not readme.exists():
            continue
        yield subdir, readme


def write_doc(path: str, content: str, source: Path | None = None) -> None:
    """
    Write documentation either through mkdocs-gen-files (during builds) or to disk.
    """
    if mkdocs_gen_files:
        with mkdocs_gen_files.open(path, "w") as f:
            f.write(content)
        if source:
            mkdocs_gen_files.set_edit_path(path, source.as_posix())
    else:
        target = docs_dir / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")


bundle_entries: list[tuple[str, str]] = []

for subdir, readme in iter_bundle_readmes(bundles_dir.iterdir()):
    markdown = readme.read_text(encoding="utf-8")
    title = extract_heading(markdown) or format_title(subdir.name)
    target_rel = f"golden-paths/databricks-bundles/{subdir.name}.md"
    autogenerated_notice = (
        f"<!-- Autogenerated from {readme.relative_to(Path('.'))}. "
        "Do not edit directly. -->\n\n"
    )
    write_doc(target_rel, autogenerated_notice + markdown, source=readme)
    bundle_entries.append((title, target_rel))
    print(f"Wrote {target_rel}")

if not bundle_entries:
    print("No bundle READMEs found; nothing to do.")
    exit(0)

# Build overview page content
content_lines = [
    "# Databricks Bundles",
    "",
    "Oversikt over eksempelbundler tilgjengelig i dette repoet.",
    "",
]

for title, target in bundle_entries:
    rel_path = Path(target).relative_to(Path(index_doc_path).parent)
    content_lines.append(f"## {title}")
    content_lines.append(f"- [Detaljert dokumentasjon]({rel_path.as_posix()})")
    content_lines.append("")

write_doc(index_doc_path, "\n".join(content_lines).rstrip() + "\n")
print(f"Generated overview {index_doc_path}")

# Update navigation so each bundle page appears under Golden Paths > Databricks Bundles
if not mkdocs_file.exists():
    print(f"Warning: {mkdocs_file} not found")
    exit(0)

with open(mkdocs_file, encoding="utf-8") as f:
    config = load_yaml(f)

if not config or "nav" not in config:
    print(f"Warning: Could not find 'nav' section in {mkdocs_file}")
    exit(0)

bundle_nav = [{"Oversikt": "golden-paths/databricks-bundles.md"}]
for title, target in bundle_entries:
    bundle_nav.append({title: target})

nav = config["nav"]


def replace_databricks_section(section: list) -> bool:
    for idx, entry in enumerate(section):
        if isinstance(entry, dict) and "Databricks Bundles" in entry:
            section[idx] = {"Databricks Bundles": bundle_nav}
            return True
        if isinstance(entry, dict):
            for _, value in entry.items():
                if isinstance(value, list) and replace_databricks_section(value):
                    return True
    return False


if replace_databricks_section(nav):
    with open(mkdocs_file, "w", encoding="utf-8") as f:
        dump_yaml(config, f)
    print(f"Updated navigation in {mkdocs_file}")
else:
    print("Warning: Could not locate 'Databricks Bundles' entry in mkdocs navigation.")
