[project]
name = "api_ingest"
version = "0.1.0"
authors = [{ name = "ola.nordmann@example.org" }]
requires-python = ">= 3.11"
dependencies = [
    "requests>=2.32",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
setup = "api_ingest.setup:main"
ingest = "api_ingest.ingest:main"

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = [
    "tests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/api_ingest"]
