name: CD
on:
  pull_request:
    branches: ["main"]
permissions:
  id-token: write
  contents: read
jobs:
  generate_lambda_matrix:
    runs-on: ubuntu-latest
    outputs:
      dev: ${{ steps.list-dirs-dev.outputs.dev }}
    steps:
      - uses: actions/checkout@v4
      - id: list-dirs-dev
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(/bin/find ./lambdas/dev -mindepth 1 -maxdepth 1 | jq -R . | jq -s . | jq -c .)
          echo "dev=$DIRS" >> $GITHUB_OUTPUT
      - id: list-dirs-stage
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(/bin/find ./lambdas/stage -mindepth 1 -maxdepth 1 | jq -R . | jq -s . | jq -c .)
          echo "stage=$DIRS" >> $GITHUB_OUTPUT
      - id: list-dirs-prod
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(/bin/find ./lambdas/prod -mindepth 1 -maxdepth 1 | jq -R . | jq -s . | jq -c .)
          echo "prod=$DIRS" >> $GITHUB_OUTPUT
  deploy_lambda_dev:
    needs: generate_lambda_matrix
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        directory: ${{ fromJson(needs.generate_lambda_matrix.outputs.dev) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: "arn:aws:iam::316489803684:role/padda_workspace_deploy"
          role-session-name: samplerolesession
          aws-region: "eu-west-1"
      - name: Upload lambda function code
        run: |
          zip /tmp/padda_test_pull_lambda.zip lambdas/padda_test_pull_lambda/pull.py
          aws lambda update-function-code --function-name padda_test_pull_lambda --zip-file fileb:///tmp/padda_test_pull_lambda.zip
