name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  generate_dir_matrix:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.list-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@v4
      - id: list-dirs
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(find ./tf -mindepth 2 -maxdepth 2 -type d -not -path './tf/modules*' | jq -R . | jq -s . | jq -c .)
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT
  validate_configurations:
    needs: generate_dir_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.generate_dir_matrix.outputs.directories) }}
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Set up SSH
        run: |
          whoami
          mkdir -p ~/.ssh
          echo "${{ secrets.GOLDEN_PATH_IAC_PRIVATE_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cp .github/known_hosts ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
          chmod 700 ~/.ssh/id_ed25519
      - name: Init ${{matrix.directory}}
        run: terraform init -backend=false
        working-directory: ${{ matrix.directory }}
      - name: Checking formatting of ${{matrix.directory}}
        run: terraform fmt -check
        working-directory: ${{ matrix.directory }}
      - name: Validate ${{matrix.directory}}
        run: terraform validate
        working-directory: ${{ matrix.directory }}
