name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  generate_python_dir_matrix:
    runs-on: ubuntu-latest
    outputs:
      directories: ${{ steps.list-dirs.outputs.dirs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - id: list-dirs
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(find ./libs -mindepth 1 -maxdepth 1 | jq -R . | jq -s . | jq -c .)
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT
  validate_python_libs:
    needs: generate_python_dir_matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.generate_python_dir_matrix.outputs.directories) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41
        with:
          version: "latest"
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14"
      - name: Format ${{matrix.directory}}
        run: uv format --check
        working-directory: ${{ matrix.directory }}
      - name: Lint ${{matrix.directory}}
        run: uvx ruff check .
        working-directory: ${{ matrix.directory }}
