name: CI
on:
  pull_request:
    branches: ["main"]
jobs:
  generate_dir_matrices:
    runs-on: ubuntu-latest
    outputs:
      pythonlibs: ${{ steps.list-libs.outputs.dirs }}
      bundles: ${{ steps.list-bundles.outputs.dirs }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - id: list-libs
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(find ./libs -mindepth 1 -maxdepth 1 | jq -R . | jq -s . | jq -c .)
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT
      - id: list-bundles
        run: |
          # Generate a JSON array of directory names (e.g., '["dir1", "dir2"]')
          DIRS=$(find ./examples -mindepth 1 -maxdepth 1 | jq -R . | jq -s . | jq -c .)
          echo "dirs=$DIRS" >> $GITHUB_OUTPUT
  validate_python_libs:
    needs: generate_dir_matrices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.generate_dir_matrices.outputs.pythonlibs) }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41
        with:
          version: "latest"
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version: "3.14"
      - name: Format ${{matrix.directory}}
        run: uv format --check
        working-directory: ${{ matrix.directory }}
      - name: Typecheck ${{matrix.directory}}
        run: uvx ty check .
        working-directory: ${{ matrix.directory }}
      - name: Lint ${{matrix.directory}}
        run: uvx ruff check .
        working-directory: ${{ matrix.directory }}
  validate_bundles:
    needs: generate_dir_matrices
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.generate_dir_matrices.outputs.bundles) }}
    steps:
      - uses: actions/checkout@v4
      - uses: databricks/setup-cli@main
      - name: Validate ${{matrix.directory}}
        run: databricks bundle validate
        working-directory: ${{ matrix.directory }}
